name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pdo, pdo_mysql

    - name: Install PHP dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run front-end build
      run: npm run build
